config/routes.rb
Rails.application.routes.draw do

  get '/mostrar_tabla_control' => 'controls#mostrar_tabla_control'

  get '/asignar_fabricacion', :to=>"controls#asignar_fabricacion"

  get 'controls/duplicar_registro/' => 'controls#duplicar_registro'

  get 'controls/planning/' => 'controls#planning'

  get 'exportar', to: 'controls#exportar', as: :controls_exportar

  resources :product_types
  resources :controls
  resources :vidres
  resources :auditvs
  resources :trampas
  resources :audits
  get 'home/principal'
  get 'home/menu_qualitat' => "home#menu_qualitat"
  get 'home/index' => "home#index"
  get 'home/menu_auditories' => "home#menu_auditories"

  root :to => "home#principal"

end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_types }
    end
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
    @product_type = ProductType.find(params[:id])

     respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/new
  # GET /product_types/new.json
  def new
    @product_type = ProductType.new

   # respond_to do |format|
   #   format.html # new.html.erb
   #   format.json { render json: @product_type }
   # end
  end

  # GET /product_types/1/edit
  def edit
    @product_type = ProductType.find(params[:id])
  end

  # POST /product_types
  # POST /product_types.json
  def create
    #@product_type = ProductType.new(params[:product_type])
    @product_type = ProductType.new(product_type_params)


    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, :flash => { :success => "Tipus de Control creat amb exit" }}
        format.json { render json: @product_type, status: :created, location: @product_type }
      else
        format.html { render action: "new" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_types/1
  # PUT /product_types/1.json
  def update
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      if @product_type.update_attributes(product_type_params)
        format.html { redirect_to @product_type, :flash => { :success => "Tipus de Control actualitzat" }}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type = ProductType.find(params[:id])
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url, :flash => { :error => "Tipus de Control esborrat" }}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:name, :frecuencia, :dataproximcontrol, fields_attributes: [:id, :name, :field_type, :required, :llistat, :product_type_id, :_destroy])
      #params.require(:product_type).permit!
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_field_fields.html.erb
<fieldset>
  <%= f.select :field_type, %w[text area_de_text check_box numeric sino dropdown1] %>
  <%= f.text_field :name, placeholder: "nom_del_camp" %>
  <%= f.check_box :required %> <%= f.label "Requerit" %>
  <%= f.check_box :llistat %> <%= f.label "Llistat" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Eliminar camp", '#', class: "remove_fields btn btn-primary" %>
</fieldset>

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> ha impedit que es guardes aquest Tipus de Control:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <label> <%= f.label "Nom Control" %></label>
          <%= f.text_field :name, :class => "form-control" %>
  </div>

    <div class="form-group">
      <label> <%= f.label "Frequència actual" %></label>
      <%= f.text_field :frecuencia, :class => "form-control",:readonly => true %>
    </div>

  <div class="form-group">
      <%= f.label "Selecciona frequència" %><br>
      <%= f.select(:frecuencia, ProductType::FRECUENCIA,{:prompt => "Selecciona frecuencia" } ,  :class=>'form-control') %>
  </div>

  <hr>

    <%= f.fields_for :fields do |builder| %>
        <%= render 'field_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Afegir camp", f, :fields %>
<br>
<br>
  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Crear nou Tipus de Control" : "Actualitzar Tipus de Control"), :class=>'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1 class="jumbotron">Editar tipus de Control</h1>

<%= render 'form' %>
</br>
<%= link_to 'Veure', @product_type, :class=>'btn btn-primary btn-block' %>
</br>
</br>
<%= link_to 'Enrera', product_types_path, :class=>'btn btn-primary btn-block' %>




<script>
  /*Esto lo he tenido que sacar de 'productypes.js.coffee' porque no se disparaba. Ver que ·$·" pasa*/
  $(document).on('click', 'form .remove_fields', function(event) {
    $(this).prev('input[type=hidden]').val('1');
    //$(this).closest('fieldset').hide();
    $(this).parent().hide();
    return event.preventDefault();
    //alert("removes");
  });

  $(document).on('click', 'form .add_fields', function(event) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });
</script>

app/views/product_types/index.html.erb
<script src="/assets/ap-scroll-top-codigo.js"></script>

<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Tipus de Controls</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.name %></td>
        <td><%= link_to 'Veure', product_type, :class=>'btn btn-primary btn-block' %></td>
        <td><%= link_to 'Editar', edit_product_type_path(product_type), :class=>'btn btn-warning btn-block' %></td>
        <td><%= link_to 'Esborrar', product_type, method: :delete, data: { confirm: 'Esborrar Tipus de Control. Estas segur?' }, :class=>'btn btn-danger btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Crear nou Tipus de Control', new_product_type_path, :class=>'btn btn-primary btn-block' %>
<br>
<%= link_to 'Tornar a Controls', controls_path, :class=>'btn btn-primary btn-block' %>
<br>
<%= paginate @product_types %>
<%= page_entries_info @product_types %>

app/views/product_types/new.html.erb
<h1 class="jumbotron">Nou Tipus de Control</h1>

<%= render 'form' %>
<br>
<%= link_to 'Cancel·lar', product_types_path, :class=>'btn btn-primary btn-block' %>


<script>
  /*Esto lo he tenido que sacar de 'productypes.js.coffee' porque no se disparaba. Ver que ·$·" pasa*/
  $(document).on('click', 'form .remove_fields', function(event) {
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('fieldset').hide(250);
    return event.preventDefault();
  });

  $(document).on('click', 'form .add_fields', function(event) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });
</script>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @product_type.name %>
</p>

<%= render 'form' %>
</br>
<%= link_to 'Editar', edit_product_type_path(@product_type),  :class=>'btn btn-primary btn-block' %>
</br>
<%= link_to 'Enrera', product_types_path,  :class=>'btn btn-primary btn-block' %>