config/routes.rb
Rails.application.routes.draw do

  get '/mostrar_tabla_control' => 'controls#mostrar_tabla_control'

  get '/asignar_fabricacion', :to=>"controls#asignar_fabricacion"

  get 'controls/duplicar_registro/' => 'controls#duplicar_registro'

  get 'controls/planning/' => 'controls#planning'

  get 'exportar', to: 'controls#exportar', as: :controls_exportar

  resources :product_types
  resources :controls
  resources :vidres
  resources :auditvs
  resources :trampas
  resources :audits
  get 'home/principal'
  get 'home/menu_qualitat' => "home#menu_qualitat"
  get 'home/index' => "home#index"
  get 'home/menu_auditories' => "home#menu_auditories"

  root :to => "home#principal"

end

app/models/control.rb
class Control < ActiveRecord::Base
  belongs_to :product_type
  serialize :properties, Hash

  #mount_uploader :foto, FotoUploader

  FRECUENCIA = ["Segons lot", "Diaria", "Setmanal", "Mensual", "Anual"]

  RESPONSABLE = ["LMF", "MRP", "JTB"]

  # ----------------------------------------------------------------------------------------------------------------
  #Exportacion a CSV

  def self.to_csv(options = {})

    #attributes = %w{id nom datacontrol operari properties}

    attributes = %w{id nom datacontrol operari}

    CSV.generate(options) do |csv|

      csv.add_row column_names

      all.each do |foo|
        #values = foo.attributes.values
        #values = (foo.properties.attributes.values)
        values = attributes.map{ |attr| foo.send(attr) }
        foo.properties.each do |name, value|
          if foo.properties.present?
              values += [name]
              values += [value]
          end
      end

      csv.add_row values

      end
    end
  end

=begin
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

  def users_to_csv(controls)
    CSV.generate do |csv|
      csv << ["Id", "nom"]
      controls.each do |user|
        csv << [control.id, control.nom ]
      end
    end
  end
=end
  # ----------------------------------------------------------------------------------------------------------------

  #SCOPES . Substituyen a self.searchX . USO : @var = Modelo.scope(algo) . Usar en controller
  #ej: @controls = Control.nomoperari(params[:search]).order(sort_column + ' ' + sort_direction).page(params[:page]).per(numpaginas) if params[:search].present?

  scope :nomcontrol, -> (nom) { where("nom like ?", "#{nom}%")}

  scope :nomoperari, -> (operari) { where("operari like ?", "%#{operari}%")}

  scope :datacon, -> (datacon) { where("datacontrol like ?", "%#{datacon}%")}

  #BUSQUEDAS. DEPRECATED EN FAVOR DE SCOPES.
=begin
                #Busqueda simple por caja de texto -----------------------------------------------------------------------------
                def self.search(search)
                  if search
                    where('nom LIKE ? OR datacontrol LIKE ? OR operari LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
                  else
                    #scoped     <--- deprecated en rails 4.1, poner where(nil)
                    where(nil)
                  end
                end

                #Busqueda simple por desplegable -------------------------------------------------------------------------------
                def self.search_desplegable(search_desplegable)
                  if search_desplegable
                    where('nom LIKE ?', "%#{search_desplegable}%")
                  else
                    #scoped     <--- deprecated en rails 4.1, poner where(nil)
                    where(nil)
                  end
                end

                #Busqueda combinada (nuevo  -------------------------------------------------------------------------------
                def self.search_combinado(search_desplegable)
                  if search_desplegable
                    where('nom LIKE ? OR datacontrol LIKE ? OR operari LIKE ?', "%#{search_desplegable}%", "%#{search_desplegable}%","%#{search_desplegable}%" )
                  else
                    #scoped     <--- deprecated en rails 4.1, poner where(nil)
                    where(nil)
                  end
                end

                #Busqueda simple por frecuencia, lista controles segun les toca o les ha pasado la fecha ------------------------
                #WIP, probablemente deadend (principios setiembre 2016)
                def self.search_frecuencia(search_frecuencia)
                  if search_frecuencia
                    where('frecuencia LIKE ? ', "%#{search_frecuencia}%")
                  else
                    #scoped     <--- deprecated en rails 4.1, poner where(nil)
                    where(nil)
                  end
                end
=end
  # ----------------------------------------------------------------------------------------------------------------

  validate :validate_properties

    def validate_properties
      product_type.fields.each do |field|
        if field.required? && properties[field.name].blank?
          errors.add field.name, "no pot estar buit"
        end
      end
    end

  # ----------------------------------------------------------------------------------------------------------------

end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  before_action :set_control, only: [:show, :edit, :update, :destroy]

  #Disponible en to el controller
  #query que hacemos en muchos metodos (asignar_fabricaciones es especial)
    #duplicar_registro
    #planning
    #new
    #edit
  before_action :definir_fabricaciones #only: [:duplicar_registro, :planning, :new, :edit]

  helper_method :sort_column, :sort_direction

  # ----------------------------------------------------------------------------------------------------------------------
  def definir_fabricaciones
    #lista general de fabricaciones
    @fabs = Fabricacio.find_by_sql("select DISTINCT TOP 25 * from
                                    (
                                    select 'Arboreto' NomEmp, C.Codigo, C.Fecha, M.NombreFabricacion
                                    froM Gest02..FabricacioCAP C LEFT join Gest02..FabricacioCapMy M on C.Codigo = M.Codigo
                                    WHERE C.OrdenFabricacion = 1  AND Codproyecto <> 'CERRADA'
                                    UNION
                                    select 'Crisol' NomEmp, C.Codigo, C.Fecha, M.NombreFabricacion
                                    froM Gest31..FabricacioCAP C LEFT join Gest31..FabricacioCapMy M on C.Codigo = M.Codigo
                                    WHERE C.OrdenFabricacion = 1  AND Codproyecto <> 'CERRADA'
                                    ) A
                                    ORDER BY Fecha DESC")
  end
# ----------------------------------------------------------------------------------------------------------------------
  def numpaginas
    numpaginas = 50
  end
# ----------------------------------------------------------------------------------------------------------------------
  def mostrar_tabla_control
    @todos =  Control.where("product_type_id = ?", params[:product_type_id])

    logger.info params[:product_type_id]

    respond_to do |format|
      format.js { @todos }
    end
  end
# ----------------------------------------------------------------------------------------------------------------------
  #asignar fabricacion a cabecera control
  def asignar_fabricacion

    #Aqui no es necesario hacer una consulta, solo queremos la fabricacion
    #Por lo que devolvemos el mismo param[:id] que se envia al servidor
    #Hago la consulta para dejar espacio al futuro para mas consultas

    #Notar que SOLO SELECCIONAMOS UN CAMPO AQUI >> Codigo
#=begin
    @mifab = Fabricacio.find_by_sql("select DISTINCT TOP 25 * from
                                    (
                                    select C.Codigo
                                    froM Gest02..FabricacioCAP C LEFT join Gest02..FabricacioCapMy M on C.Codigo = M.Codigo
                                    WHERE C.OrdenFabricacion = 1 AND Codproyecto <> 'CERRADA' AND C.Codigo = '#{params[:id]}'
                                    UNION
                                    select C.Codigo
                                    froM Gest31..FabricacioCAP C LEFT join Gest31..FabricacioCapMy M on C.Codigo = M.Codigo
                                    WHERE C.OrdenFabricacion = 1  AND Codproyecto <> 'CERRADA' AND C.Codigo = '#{params[:id]}'
                                    ) A")
#=end
   #render :text => @mifab.first.Codigo

   #render plain: @mifab.first.Codigo

    #Codigo funciona porque esta incluido en las tablas de la BD
    #Funciona con Codigo, Fecha, NombreFabricacion,NomEmp
    @micodigo = @mifab.first.Codigo

    respond_to do |format|
      #format.js { @mifab }
      format.js { @micodigo }
      #format.js { params[:id] }
      #format.js { @mifab.first.Codigo }
      #format.js { params[:id] } <-------------- dejar esto si solo queremos el codigo fabricacion
    end

    #logger.info 'Resultado: ' + @mifab

  end
# ----------------------------------------------------------------------------------------------------------------------
  #duplica un registro, sin copiar la :id
  def duplicar_registro
    #buscamos el control
      @original = Control.find(params[:id])
    #lo duplicamos
      @control = @original.dup
    #solo queremos la cabecera, ponemos las propiedades a 0
      @control.properties = {}
    #ponemos fecha actual
      @control.datacontrol = Time.now
  end
# ----------------------------------------------------------------------------------------------------------------------
  def planning

    #nota: voy a cambiar todos los time.now a time.zone.now. CHECK it . Solo los 3 primeros estaban con time.zone.now
    #test
    @todos =  Control.where(:nom => 'ControlsTest')

    #hechos hoy
    @controls_avui = Control.where("created_at >= ?", Time.zone.now.beginning_of_day).page(params[:page]).per(numpaginas)

    #hechos con fecha antes que hoy
    @controls_anteriors = Control.where("created_at < ?", Time.zone.now.beginning_of_day).page(params[:page]).per(numpaginas)

    #Controles atrasados
    @controls_endarrerits = Control.where("dataproximcontrol < ?", Time.zone.now.beginning_of_day).page(params[:page]).per(numpaginas)

    #controles que toca hacer hoy (:dataproximcontrol)
    @controls_per_fer_avui = Control.where(:dataproximcontrol => Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).page(params[:page]).per(numpaginas)

    #controles que toca hacer la semana que viene (:dataproximcontrol)
    @controls_per_fer_setmana = Control.where(:dataproximcontrol => Time.zone.now.next_week..Time.zone.now.next_week.end_of_week).page(params[:page]).per(numpaginas)

    #controles que toca hacer esta semana
    @controls_per_fer_aquesta_setmana = Control.where(:dataproximcontrol => Time.zone.now..Time.zone.now.end_of_week).page(params[:page]).per(numpaginas)

    #controles que toca hacer el mes que viene (:dataproximcontrol)
    #@controls_per_fer_mes = Control.where(:dataproximcontrol => Time.now.next_month..Time.now.next_month.end_of_month).page(params[:page]).per(numpaginas)
    @controls_per_fer_mes = Control.where(:dataproximcontrol => Time.zone.now.next_month.beginning_of_month..Time.zone.now.next_month.end_of_month).page(params[:page]).per(numpaginas)

    #fabs = sql etc etc

    respond_to do |format|
      format.html
    end
  end
# ----------------------------------------------------------------------------------------------------------------------
  #exportacion CSV, mirar MODEL tambien
  def exportar

    #@datos es nil . mejor dicho. @controls es nil, arreglar
    @datos = @@busqueda

    respond_to do |format|
      format.html { redirect_to root_url }
      format.csv { send_data @datos.to_csv, :type => 'text/csv; charset=iso-8859-1; header=present', filename: "controls-#{Date.today}.csv" }
      #format.csv { render text: @datos.to_csv }
    end
  end
# ----------------------------------------------------------------------------------------------------------------------
  # GET /controls
  # GET /controls.json
  def index
    #original sin search
    #@controls = Control.all.page(params[:page]).per(50).order(sort_column + " " + sort_direction)

    #nota: @@busqueda en raras ocasiones da error 'not initialized', buscar y evitar

  #Listado con busqueda . search=textbox, datacon=datepicker, search_desplegable=desplegable
  if params[:search].present? and params[:datacon].present? and params[:search_desplegable].present?
      @controls = Control.nomoperari(params[:search]).datacon(params[:datacon]).nomcontrol(params[:search_desplegable]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  elsif params[:search].present? and params[:datacon].present?
      @controls = Control.nomoperari(params[:search]).datacon(params[:datacon]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  elsif params[:search].present? and params[:search_desplegable].present?
      @controls = Control.nomoperari(params[:search]).nomcontrol(params[:search_desplegable]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  elsif params[:datacon].present? and params[:search_desplegable].present?
      @controls = Control.datacon(params[:datacon]).nomcontrol(params[:search_desplegable]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  elsif params[:search].present?
      @controls = Control.nomoperari(params[:search]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  elsif params[:datacon].present?
      @controls = Control.datacon(params[:datacon]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  elsif params[:search_desplegable].present?
      @controls = Control.nomcontrol(params[:search_desplegable]).order(sort_column + " " + sort_direction).page(params[:page]).per(numpaginas)
      @@busqueda = @controls
  else
      @controls = Control.all.page(params[:page]).per(50).order(sort_column + " " + sort_direction)
      @@busqueda = @controls
  end#if

     if @@busqueda.nil?
       @@busqueda = @controls
     end

  end
# ----------------------------------------------------------------------------------------------------------------------
  # GET /controls/1
  # GET /controls/1.json
  def show
    @control = Control.find(params[:id])
    @nombre = ProductType.find_by_sql("SELECT name FROM product_types WHERE product_types.id = #{params[:id]}")
    @tipo = ProductField.find_by_sql("SELECT product_fields.field_type
            FROM controls JOIN product_types
            ON controls.product_type_id = product_types.id
            JOIN product_fields
            ON product_fields.product_type_id = product_types.id
            WHERE controls.id = #{params[:id]}")
  end
  #innecesario
  #def nombre_control

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/_formshow.html.erb
<%= form_for(@control) do |f| %>

<table>
  <thead>
    <tr>
        <td>    </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>      </td>
    </tr>
  </tbody>
</table>

  <div class="field">
    <%= f.label "Nom Control" %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label "Data Control" %><br>
    <%= f.datetime_select :datacontrol, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :operari %><br>
    <%= f.text_field :operari %>
  </div>

    <hr>
    <!-- Separamos visualmente cabecera y campos del control -->

    <%= f.fields_for :properties, OpenStruct.new(@control.properties) do |builder| %>
        <% @control.product_type.fields.each do |field| %>
            <%= render "controls/fields/#{field.field_type}", field: field, f: builder %>
        <% end %>
    <% end %>

    <br>

<% end %>

app/views/controls/_mostrar_tabla_control.html.erb
<h5>Test Parcial</h5>

<% if @todos.empty? %>
    <p>Error: Sin datos</p>
<% else %>

    <table class="table" border="1">
      <caption><%= @todos[0].nom %><b> | Total controls: </b><%= @todos.count %></caption>
      <thead>
        <tr>

          <th>Datacontrol</th>
          <% i = 0 %>
          <% while i < @todos[0].properties.keys.count %>
              <th><%= @todos[0].properties.keys[i] %></th>
              <% i += 1 %>
          <% end %>

        </tr>
      </thead>
      <tbody>

      <% @todos.each do |control| %>
          <tr>
            <td><%= control.datacontrol.strftime('%d-%m-%Y') %></td>
            <% control.properties.each do |properties| %>
                <td>
                  <%= properties[1] %>
                </td>
            <% end %>
          </tr>
      <% end %>

      </tbody>
    </table>

<% end %>

app/views/controls/asignar_fabricacion.js.erb
/**
 * Created by Fran on 21/11/2016.
 */
$("#fabtext").val("<%= @micodigo %>").effect('highlight', {}, 3000);

app/views/controls/duplicar_registro.html.erb
<script>
  $(function() {
    $("#accordion:nth-child(1n)" ).accordion({
      heightStyle: "content",
      active: false,
      collapsible: true
    });
  });
</script>

<h1 class="jumbotron">Editar Duplicació de Control</h1>

<%= render 'form' %>
<!-- </br>
<%= link_to 'Veure', @control, :class=>'btn btn-primary btn-block' %> -->
</br>
</br>
<%= link_to 'Enrera', controls_path, :class=>'btn btn-primary btn-block' %>

app/views/controls/edit.html.erb
<script>
  $(function() {
    $("#accordion:nth-child(1n)" ).accordion({
      heightStyle: "content",
      active: false,
      collapsible: true
    });
  });
</script>

<h1 class="jumbotron">Editar Control</h1>

<%= render 'form' %>
</br>
<%= link_to 'Veure', @control, :class=>'btn btn-primary btn-block' %>
</br>
</br>
<%= link_to 'Enrera', controls_path, :class=>'btn btn-primary btn-block' %>

app/views/controls/index.html.erb
<script>
  $.datepicker.regional['ca'] = {
    closeText: 'Tancar',
    prevText: '<Ant',
    nextText: 'Seg>',
    currentText: 'Avui',
    monthNames: ['Gener', 'Febrer', 'Març', 'Abril', 'Maig', 'Juny', 'Juliol', 'Agost', 'Setembre', 'Octubre', 'Novembre', 'Decembre'],
    monthNamesShort: ['Gen','Feb','Mar','Abr', 'Mai','Jun','Jul','Ago','Set', 'Oct','Nov','Dec'],
    dayNames: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],
    dayNamesShort: ['Dg','Dl','Dt','Dc','Dj','Dv','Ds'],
    dayNamesMin: ['Dg','Dl','Dt','Dc','Dj','Dv','Ds'],
    weekHeader: 'Sm',
    /*dateFormat: 'dd/mm/yy',*/
    dateFormat: 'yy-mm-dd',
    altField: "#datacon",
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: ''
  };
  $.datepicker.setDefaults($.datepicker.regional['ca']);
  $(function () {
    $("#datepicker").datepicker();
  });
</script>

<script src="/assets/ap-scroll-top-codigo.js"></script>

<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Històric de Controls</h1>

<% if @controls.empty? %>
    <p align="center"><strong>No s'han trobat controls</strong></p>
<% end %>

<!-- nuevo UI busqueda -->
<br>
<div class="borde-normal">
  <table style="/*width:100%;*/">
    <thead></thead>
    <th  colspan="5"></th>
    <tbody>
    <tr>
      <%= form_tag controls_path, :method => 'get' do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>

          <td><p>
            <%= text_field_tag :search, params[:search], :class=>"form-control" %>
          </p></td>

          <td><p>Data: <input type="text" id="datepicker"></p></td>

         <td style="display:none;"><p><%= text_field_tag :datacon %></p></td>

          <td> <p>
            <%= select_tag :search_desplegable, options_from_collection_for_select(ProductType.all.order('created_at desc'), :name, :name), prompt: "-Selecciona tipus a buscar-", :class=>"form-control" %>
          </p></td>

          <td><p>
            <%= submit_tag "Buscar", :name => nil, :class=>"form-control btn btn-primary btn-block" %>
          </p></td>

          <td> <p>
            <%= link_to "Reset", '#', onclick: 'document.getElementById("search").value="";document.getElementById("search_desplegable").value=""; return false;', class: "form-control btn btn-warning btn-block" %>
          </p></td>
      <% end %>
    </tr>
    </tbody>
  </table>
</div>
<!-- fin nuevo UI busqueda -->

<br>

<div>
  <%= link_to 'Plànning de Controls', 'controls/planning/', :class=>'btn btn-primary btn-block' %>
</div>

<script>
  function borrarTexto() {document.getElementById("search").value="";}
</script>

<br>

<h4>Seleccionar tipus de control per crear:</h4>
<%= form_tag new_control_path, method: :get do %>
    <div class="form-group"> <%= select_tag :product_type_id, options_from_collection_for_select(ProductType.all.order('created_at desc'), :id, :name), :class=>"form-control" %> </div>
    <%= submit_tag "Nou Control", name: nil, :class=>'btn btn-primary btn-block' %>
<% end %>
<br>
<%= link_to 'Gestionar Tipus de Controls', product_types_path, :class=>'btn btn-primary btn-block' %>
<br>
<br>
<%= link_to 'Enrera', home_menu_qualitat_path, :class=>'btn btn-primary btn-block' %>

<br>

<table class="table table-striped">
  <thead>
    <tr>
    <!--   <th><%= sortable "id" %></th> -->
      <th><%= sortable "nom" %></th>
      <th><%= sortable "datacontrol","Data Control" %></th>
      <th><%= sortable "operari" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @controls.each do |control| %>
      <tr>
     <!--    <td><%= control.product_type_id %></td> -->
        <td><%= control.nom %></td>
        <td><%= control.datacontrol.strftime('%d-%m-%Y') %> / <%= control.datacontrol.strftime('%H:%M')%></td>
        <td><%= control.operari %></td>
        <td><%= link_to 'Veure', control, :class=>'btn btn-primary btn-block' %></td>
        <td><%= link_to 'Editar', edit_control_path(control), :class=>'btn btn-warning btn-block' %></td>
        <td><%= link_to 'Esborrar', control, method: :delete, data: { confirm: 'Esborrar Control i totes les dades associades. Estas segur?' }, :class=>'btn btn-danger btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- ubicacion original Select tipo control -->
<br>
<table style="margin-left:auto;margin-right:auto;">
  <tr>
    <td>
      <a href="#" onclick="window.print();return false;">Imprimir</a> /
    </td>
    <td>
      <%= link_to "Exportar CSV", controls_exportar_path(format: "csv") %> /
    </td>

    <td>
      <%= link_to "Exportar CSV TEST", controls_exportar_path(format:"csv") %>
    </td>
  </tr>
</table>
<br>

<%= paginate @controls %>
<%= page_entries_info @controls %>

app/views/controls/mostrar_tabla_control.js.erb
/**
 * Created by Fran on 29/11/2016.
 */

$("#planning").html("<%= escape_javascript(render partial: 'mostrar_tabla_control' ) %>");

app/views/controls/new.html.erb
<script>
  $(function() {
    $("#accordion:nth-child(1n)" ).accordion({
      heightStyle: "content",
      active: false,
      collapsible: true
    });
  });
</script>

<h1 class="jumbotron">Crear nou Control</h1>

<%= render 'form' %>
</br>
<%= link_to 'Cancel·lar', controls_planning_path, :class=>'btn btn-primary btn-block' %>

app/views/controls/show.html.erb
<script>
  $( function() {
    $( "#accordion" ).accordion({
      collapsible: true,
      active: false
    });
  } );
</script>

<p id="notice"><%= notice %></p>

<div class ="well">
  <table class="table">
    <tbody>
    <tr>
      <td>
        <p>
          <strong>Nom:</strong>
        </p>
      </td>
      <td>
        <p>
          <%= @control.nom %>
        </p>
      </td>
    </tr>

    <tr>
      <td>
        <p>
          <strong>Data Control:</strong>
        </p>
      </td>
      <td>
        <p>
          <%= @control.datacontrol.strftime('%d-%m-%Y') %> / <%= @control.datacontrol.strftime('%H:%M')%>
        </p>
      </td>
    </tr>

    <tr>
      <td>
        <p>
          <strong>Operari:</strong>
        </p>
      </td>
      <td>
        <p>
          <%= @control.operari %>
        </p>
      </td>
    </tr>

    <tr>
      <td>
        <p>
          <strong>Freqüència:</strong>
        </p>
      </td>
      <td>
        <p>
          <% if @control.frecuencia.nil? || @control.frecuencia == 'Selecciona frecuencia' %>
              Freqüència no establerta
          <% else %>
              <%= @control.frecuencia %>
          <% end %>
        </p>
      </td>
    </tr>

    <tr>
      <td>
        <p>
          <strong>Proper control:</strong>
        </p>
      </td>
      <td>
        <p>
          <% if @control.dataproximcontrol.nil? %>
              No informat
          <% else %>
              <%= @control.dataproximcontrol.strftime('%d-%m-%Y') %>
          <% end %>
        </p>
      </td>
    </tr>


    <tr>
      <td>
        <p>
          <strong>Fabricació:</strong>
        </p>
      </td>
      <td>
        <p>
          <% if @control.fabricacio.nil? %>
              Sense fabricació asignada
          <% else %>
              <%= @control.fabricacio %>
          <% end %>
        </p>
      </td>
    </tr>

    </tbody>
  </table>
</div>

<br>

<!-- ciclar entre los diferentes valores. Hay una lista de valores y una lista de campos, y se integran -->
<% if @control.product_type.nil? %>
    <p>Error: Tipus de control per aquest control no existeix. ID Tipus: <%= @control.product_type_id %></p>
<% else %>
    <table class="table table-striped">
      <% @control.product_type.fields.each do |field1| %>
          <tr>
            <td><b><%= field1.name %></b></td>

            <% @campo = field1 %>

            <% if field1.field_type == 'check_box' %>

                <% @campo = field1 %>

                <% @control.properties.each do |name, value| %>
                    <% @valor = value %>
                    <% if @campo != nil %>
                        <% if @campo.name == name %>
                            <% if value == '1' %>
                                <td><div><%= check_box_tag(nil, 1, true, options = {:disabled => true}) %></div></td>
                            <% else %>
                                <td><div><%= check_box_tag(nil, 1, false, options = {:disabled => true}) %></div></td>
                            <% end %>
                        <% else %>
                            <% @valor = value %>
                        <% end %>
                    <% else %>
                        <% if @campo.name != name %>
                            <td><%= value %></td>
                        <% end %>
                    <% end %>
                <% end %>
            <% else %>
                <% @control.properties.each do |name, value| %>
                    <% if @campo.name == name %>
                        <td> <%= value %> </td>
                    <% end %>
                <% end %>
            <% end %>

          </tr>
      <% end %>
    </table>
<% end %>

<br>

<br>
<% if @control.product_type.nil? %>
<% else %>
    <%= link_to 'Editar', edit_control_path(@control), :class=>'btn btn-primary btn-block' %>
    <br>
<% end %>
<br>
<%= link_to 'Duplicar Control', {:controller => "controls", :action => "duplicar_registro", :id => @control.id }, :class=>'btn btn-primary btn-block' %>
<br>
<hr>
<%= link_to 'Anar a Plànning de Controls', controls_planning_path, :class=>'btn btn-primary btn-block' %>
<br>
<%= link_to 'Anar a Històric i Gestió de Controls', controls_path, :class=>'btn btn-primary btn-block' %>
<br>
<div id="accordion">
  <h3 class="well well-sm">Ajuda</h3>
  <div>
    <p>
      Ajuda contextual
    </p>
  </div>
</div>