config/routes.rb
Rails.application.routes.draw do

  get '/mostrar_tabla_control' => 'controls#mostrar_tabla_control'

  get '/asignar_fabricacion', :to=>"controls#asignar_fabricacion"

  get 'controls/duplicar_registro/' => 'controls#duplicar_registro'

  get 'controls/planning/' => 'controls#planning'

  get 'exportar', to: 'controls#exportar', as: :controls_exportar

  resources :product_types
  resources :controls
  resources :vidres
  resources :auditvs
  resources :trampas
  resources :audits
  get 'home/principal'
  get 'home/menu_qualitat' => "home#menu_qualitat"
  get 'home/index' => "home#index"
  get 'home/menu_auditories' => "home#menu_auditories"

  root :to => "home#principal"

end

app/models/audit.rb
class Audit < ActiveRecord::Base
	has_many :trampas,  dependent: :destroy
	accepts_nested_attributes_for :trampas

	#product = lo que queremos exportar
	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |product|
				csv << product.attributes.values_at(*column_names)
			end
		end
	end


end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
  #http_basic_authenticate_with name: "joan", password: "tio", except: :index

  before_action :set_audit, only: [:show, :edit, :update, :destroy]

  # GET /audits
  # GET /audits.json
  def index
    #pre-kaminari
    #@audits = Audit.all
    #post-kaminari
    @audits = Audit.page(params[:page]).per(10)

    #exportacion a CSV
    #respond_to do |format|
    #  format.html
    #  format.csv { render text: @audits.to_csv }
    #end
    #exportacion CSV -fin
  end

  # GET /audits/1
  # GET /audits/1.json
  def show
    #@trampas = Trampa.where(:audit_id=>params[:id])

    #exportacion a CSV
    #@trampas = @audit.trampas
    #respond_to do |format|
    #  format.html
    #  format.csv { render text: @audits.to_csv }
    #end
    #exportacion CSV -fin
  end

  # GET /audits/new
  def new
    #@trampas = Trampa.where(:audit_id=>'1')
    @trampas = Trampa.where(:audit_id=>nil)
    @audit = Audit.new
    @audit.trampas << @trampas
    #@audit = Audit.new
    #@audit.trampas.build
  end

  # GET /audits/1/edit
  def edit
    #trampas = Trampa.all
    #la linea anterior estaba descomentada
    #@trampas = Trampa.where(:audit_id=>params[:id])
    @audit = Audit.find(params[:id])
    @trampas = Trampa.find_by_audit_id(:id)
  end

  # POST /audits
  # POST /audits.json
  def create
    @audit = Audit.new(audit_params)
    @trampas = Trampa.where(:audit_id=>params[:id])
    @trampas.build

    respond_to do |format|
      if @audit.save
        format.html { redirect_to @audit, notice: 'Auditoria realitzada.' }
        format.json { render :show, status: :created, location: @audit }
      else
        format.html { render :new }
        format.json { render json: @audit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audits/1
  # PATCH/PUT /audits/1.json
  def update
      respond_to do |format|
        #if @audit.update(audit_params)
        if @audit.update(cabecera_params)
          format.html { redirect_to @audit, notice: 'Auditoria actualitzada.' }
          format.json { render :show, status: :ok, location: @audit }
        else
          format.html { render :edit }
          format.json { render json: @audit.errors, status: :unprocessable_entity }
        end
      end
  end


  # DELETE /audits/1
  # DELETE /audits/1.json
  def destroy
    @audit.destroy
    respond_to do |format|
      format.html { redirect_to audits_url, notice: 'Auditoria esborrada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audit
      @audit = Audit.find(params[:id])
      @trampas = Trampa.where(:audit_id=>params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audit_params
     params.require(:audit).permit(:id, :dataaudit, :observacions, trampas_attributes: [:nom, :tipus, :recompte, :estat_ok, :observacions, :ubicacio, :foto, :fotobase])
    end
    #intento de editar solo cabecera
    def cabecera_params
      params.require(:audit).permit(:id, :dataaudit, :observacions)
    end
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/views/audits/_form.html.erb
<%= form_for(@audit) do |f|  %>
  <% if @audit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audit.errors.count, "error") %> ha impedit que es gravi correctament:</h2>

      <ul>
      <% @audit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dataaudit %><br>
    <%= f.date_select :dataaudit %>
  </div>

  <div class="field">
    <%= f.label :observacions %><br>
    <%= f.text_area :observacions %>
  </div>

    <h2>Trampes</h2>
    <div>
    <%= f.fields_for :trampas do |builder| %>
        <%= render 'trampas', f: builder %>
    <% end %>
    </div>

    </br>

  <div class="actions">
    <%= f.submit :class=>'btn btn-primary btn-block' %>
  </div>

<% end %>

<script type="text/javascript">
  /*hacer un loop de esto*/
  $('#audit_trampas_attributes_0_estat_ok').change(function(){$('#audit_trampas_attributes_0_observacions').toggle(250);});
  $('#audit_trampas_attributes_1_estat_ok').change(function(){$('#audit_trampas_attributes_1_observacions').toggle(250);});
  $('#audit_trampas_attributes_2_estat_ok').change(function(){$('#audit_trampas_attributes_2_observacions').toggle(250);});
  $('#audit_trampas_attributes_3_estat_ok').change(function(){$('#audit_trampas_attributes_3_observacions').toggle(250);});

  $('#audit_trampas_attributes_4_estat_ok').change(function(){$('#audit_trampas_attributes_4_observacions').toggle(250);});
  $('#audit_trampas_attributes_5_estat_ok').change(function(){$('#audit_trampas_attributes_5_observacions').toggle(250);});
  $('#audit_trampas_attributes_6_estat_ok').change(function(){$('#audit_trampas_attributes_6_observacions').toggle(250);});
  $('#audit_trampas_attributes_7_estat_ok').change(function(){$('#audit_trampas_attributes_7_observacions').toggle(250);});
</script>

app/views/audits/_trampas.erb
<fieldset>
  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom , :readonly => true %>
  </div>
  </br>
  <div class="field">
    <%= f.label :tipus %>
    <%= f.text_field :tipus, :readonly => true, :style => "min-width:20%" %>
  </div>
  </br>
  <div class="field">
    <%= f.label :ubicacio %>
    <%=  f.select(:ubicacio, Trampa::UBICACIO) %>
  </div>
  </br>
  <div class="field">
    <%= f.label :descripcio %>
    <%= f.text_area :descripcio %>
  </div>
  </br>
  <div class="field">
    <%= f.label :fotobase %>
    <%= f.file_field :fotobase, :accept =>'image/*' %>
  </div>
  </br>
  <div class="field">
    <%= f.label :recompte %>
    <%= f.number_field :recompte %>
  </div>
  </br>
  <div class="field">
    <%= f.label :estat_ok %>
    <%= f.check_box :estat_ok %>
  </div>
  </br>
  <div class="field">
    <%= f.label :observacions %><br>
    <%= f.text_area :observacions %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto, :accept =>'image/*' %>
  </div>
</fieldset>

app/views/audits/edit.html.erb
<h1 class="jumbotron">Editar Auditoria</h1>

<%= render 'form' %>

<%= link_to 'Veure', @audit , :class=>'btn btn-primary btn-block'%> |
<%= link_to 'Enrera', audits_path, :class=>'btn btn-primary btn-block' %>

app/views/audits/index.html.erb
<script src="/assets/ap-scroll-top-codigo.js"></script>

<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Històric d'auditories de Trampes</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Data</th>
      <th>Observacions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @audits.each do |audit| %>
      <tr>
        <td><%= audit.dataaudit.strftime('%d-%m-%Y') %> / <%= audit.created_at.strftime('%H:%M')%> <b>Propera revisio:</b> <%= (audit.created_at + 2.months).strftime('%d-%m-%Y') %> </td>
        <td><%= audit.observacions %></td>
        <td><%= link_to 'Veure', audit, :class=>'btn btn-primary btn-block' %></td>

         <td><%= link_to 'Editar capçalera', edit_audit_path(audit), :class=>'btn btn-warning btn-block' %></td>

        <td><%= link_to 'Esborrar', audit, method: :delete, data: { confirm: 'Esborrar auditoria y trampes relacionades. Estas segur?' }, :class=>'btn btn-danger btn-block' %></td>
      </tr>
    <% end.empty? %>
    No hi han auditories.
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @audits %>
<%= page_entries_info @audits %>

<br>

<div>
<%= link_to 'Nova auditoria de Trampes', new_audit_path, :class=>'btn btn-primary btn-block' %>
<%= link_to 'Plantilles de Trampes', trampas_path, :class=>'btn btn-primary btn-block' %>
  </div>
</br>
<%= link_to 'Enrera', '\home\menu_auditories', :class=>'btn btn-primary btn-block' %>
<%= link_to 'Menu Principal', home_principal_path, :class=>'btn btn-primary btn-block' %>

</br>
<!--
<% unless @audits.blank? %>
    <p>
      Descarrega:
      <%= link_to "CSV",    audits_path(format: "csv") %> |
      <%= link_to "Excel",  audits_path(format: "xls") %>
    </p>
<% end %>
-->

app/views/audits/new.html.erb
<h1 class="jumbotron">Nova auditoria de Trampes</h1>

<%= render 'form' %>
</br>
<%= link_to 'Cancel·lar', audits_path, :class=>'btn btn-primary btn-block' %>

app/views/audits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data auditoria:</strong>
  <%= @audit.dataaudit %>
</p>
<p>
  <strong>Observacions:</strong>
  <%= @audit.observacions %>
</p>
<table class="table table-condensed">
  <thead>
  <tr>
    <th>Nom</th>
    <th>Tipus</th>
    <th>Ubicacio</th>
    <th>Descripcio</th>
    <th>Foto Inicial</th>
    <th>Recompte</th>
    <th>Estat Ok</th>
    <th>Observacions</th>
    <!-- <th>Auditoria</th> -->
    <th>Foto Auditoria</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trampas.each do |trampa| %>
      <tr>
        <td><%= trampa.nom %></td>
        <td><%= trampa.tipus %></td>
        <td><%= trampa.ubicacio %></td>
        <td><%= trampa.descripcio %></td>
        <td><%= image_tag trampa.fotobase, :style => 'width:175px;height:75px;'%></td>
        <td align="center"><%= trampa.recompte %></td>
        <td><%= check_box "trampa", "estat_ok", {:checked => trampa.estat_ok, :disabled => true}%></td>
        <td><%= trampa.observacions %></td>

      <!--  <td><%= trampa.audit.id %></td> -->

        <td> <%= image_tag trampa.foto, :style => 'width:175px;height:75px;'%></td>

        <!-- <td><%= link_to 'Veure trampa', trampa %></td> -->

        <td><%= link_to 'Editar trampa', edit_trampa_path(trampa), :class=>'btn btn-primary btn-block' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</br>

<!-- <%= link_to 'Editar', edit_audit_path(@audit) %>  -->
<%= link_to 'Validar', audits_path, :class=>'btn btn-primary btn-block' %>
</br>

<!--
<p>
  Descarrega:
  <%= link_to "CSV",    audits_path(format: "csv") %> |
  <%= link_to "Excel",  audits_path(format: "xls") %>
</p>
-->