config/routes.rb
Rails.application.routes.draw do

  get '/mostrar_tabla_control' => 'controls#mostrar_tabla_control'

  get '/asignar_fabricacion', :to=>"controls#asignar_fabricacion"

  get 'controls/duplicar_registro/' => 'controls#duplicar_registro'

  get 'controls/planning/' => 'controls#planning'

  get 'exportar', to: 'controls#exportar', as: :controls_exportar

  resources :product_types
  resources :controls
  resources :vidres
  resources :auditvs
  resources :trampas
  resources :audits
  get 'home/principal'
  get 'home/menu_qualitat' => "home#menu_qualitat"
  get 'home/index' => "home#index"
  get 'home/menu_auditories' => "home#menu_auditories"

  root :to => "home#principal"

end

app/models/auditv.rb
class Auditv < ActiveRecord::Base
  has_many :vidres,  dependent: :destroy
  accepts_nested_attributes_for :vidres
end

app/controllers/auditvs_controller.rb
class AuditvsController < ApplicationController
  before_action :set_auditv, only: [:show, :edit, :update, :destroy]

  # GET /auditvs
  # GET /auditvs.json
  def index
    @auditvs = Auditv.all.page(params[:page]).per(10)
  end

  # GET /auditvs/1
  # GET /auditvs/1.json
  def show
  end

  # GET /auditvs/new
  def new
    @vidres = Vidre.where(:auditv_id=>nil)
    @auditv = Auditv.new
    @auditv.vidres << @vidres
  end

  # GET /auditvs/1/edit
  def edit
    @auditv = Auditv.find(params[:id])
    @vidres = Vidre.find_by_auditv_id(:id)
  end

  # POST /auditvs
  # POST /auditvs.json
  def create
    @auditv = Auditv.new(auditv_params)
    @vidres = Vidre.where(:auditv_id=>params[:id])
    @vidres.build

    respond_to do |format|
      if @auditv.save
        format.html { redirect_to @auditv, notice: 'Auditoria Vidres/BPH/BPM/FD realitzada.' }
        format.json { render :show, status: :created, location: @auditv }
      else
        format.html { render :new }
        format.json { render json: @auditv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditvs/1
  # PATCH/PUT /auditvs/1.json
  def update
    respond_to do |format|
      #if @auditv.update(audit_params)
      if @auditv.update(cabecera_params)
        format.html { redirect_to @auditv, notice: 'Auditoria Vidres/BPH/BPM/FD actualitzada.' }
        format.json { render :show, status: :ok, location: @auditv }
      else
        format.html { render :edit }
        format.json { render json: @auditv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auditvs/1
  # DELETE /auditvs/1.json
  def destroy
    @auditv.destroy
    respond_to do |format|
      format.html { redirect_to auditvs_url, notice: 'Auditv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auditv
      @auditv = Auditv.find(params[:id])
      @vidres = Vidre.where(:auditv_id=>params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  # Never trust parameters from the scary internet, only allow the white list through.
  def auditv_params
    params.require(:auditv).permit(:id, :dataaudit, :observacions, vidres_attributes: [:nom, :tipus, :recompte, :descripcio, :estat_ok, :observacions, :ubicacio, :foto, :fotobase])
  end
  #intento de editar solo cabecera, (con exito)
  def cabecera_params
    params.require(:auditv).permit(:id, :dataaudit, :observacions)
  end
end

app/helpers/auditvs_helper.rb
module AuditvsHelper
end

app/views/auditvs/_form.html.erb
<%= form_for(@auditv) do |f|  %>
    <% if @auditv.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@auditv.errors.count, "error") %> ha impedit que es gravi correctament:</h2>

          <ul>
            <% @auditv.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :dataaudit %><br>
      <%= f.date_select :dataaudit %>
    </div>

    <div class="field">
      <%= f.label :observacions %><br>
      <%= f.text_area :observacions %>
    </div>

    <h2>Vidres/BPM/BPH/FD</h2>
    <div>
      <%= f.fields_for :vidres do |builder| %>
          <%= render 'vidres', f: builder %>
      <% end %>
    </div>

    </br>

    <div class="actions">
      <%= f.submit :class=>'btn btn-primary btn-block' %>
    </div>

<% end %>

<script type="text/javascript">
  /*hacer un loop de esto*/
  $('#audit_trampas_attributes_0_estat_ok').change(function(){$('#audit_trampas_attributes_0_observacions').toggle(250);});
  $('#audit_trampas_attributes_1_estat_ok').change(function(){$('#audit_trampas_attributes_1_observacions').toggle(250);});
  $('#audit_trampas_attributes_2_estat_ok').change(function(){$('#audit_trampas_attributes_2_observacions').toggle(250);});
  $('#audit_trampas_attributes_3_estat_ok').change(function(){$('#audit_trampas_attributes_3_observacions').toggle(250);});

  $('#audit_trampas_attributes_4_estat_ok').change(function(){$('#audit_trampas_attributes_4_observacions').toggle(250);});
  $('#audit_trampas_attributes_5_estat_ok').change(function(){$('#audit_trampas_attributes_5_observacions').toggle(250);});
  $('#audit_trampas_attributes_6_estat_ok').change(function(){$('#audit_trampas_attributes_6_observacions').toggle(250);});
  $('#audit_trampas_attributes_7_estat_ok').change(function(){$('#audit_trampas_attributes_7_observacions').toggle(250);});
</script>

app/views/auditvs/_vidres.html.erb
<fieldset>
  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom , :readonly => true %>
  </div>
  </br>
  <div class="field">
    <%= f.label :tipus %>
    <%= f.text_field :tipus, :readonly => true, :style => "min-width:20%" %>
  </div>
  </br>
  <div class="field">
    <%= f.label :ubicacio %>
    <%=  f.select(:ubicacio, Vidre::UBICACIO) %>
  </div>
  </br>
  <div class="field">
    <%= f.label :descripcio %>
    <%= f.text_area :descripcio %>
  </div>
  </br>
  <div class="field">
    <%= f.label "Foto Inicial" %><br>
    <%= f.file_field :fotobase, :accept =>'image/*' %>
  </div>
  </br>
  <div class="field">
    <%= f.label :recompte %>
    <%= f.number_field :recompte %>
  </div>
  </br>
  <div class="field">
    <%= f.label :estat_ok %>
    <%= f.check_box :estat_ok %>
  </div>
  </br>
  <div class="field">
    <%= f.label :observacions %><br>
    <%= f.text_area :observacions %>
  </div>
  </br>
  <div class="field">
    <%= f.label "Foto Auditoria" %><br>
    <%= f.file_field :foto, :accept =>'image/*' %>
  </div>
</fieldset>

app/views/auditvs/edit.html.erb
<h1>Editar auditoria de Vidres/PD/BPH/BPM/FD/E-I</h1>

<%= render 'form' %>

<%= link_to 'Veure', @auditv, :class=>'btn btn-primary btn-block' %>
<%= link_to 'Editar', auditvs_path, :class=>'btn btn-primary btn-block' %>
</br>
<%= link_to 'Enrera', '\home\menu_auditories', :class=>'btn btn-primary btn-block' %>
<%= link_to 'Menu Principal', home_principal_path, :class=>'btn btn-primary btn-block' %>
</br>

app/views/auditvs/index.html.erb
<script src="/assets/ap-scroll-top-codigo.js"></script>

<p id="notice"><%= notice %></p>

<h1 class="jumbotron">Històric d'auditories de Vidres/PD/BPH/BPM/FD/E-I</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Data</th>
      <th>Observacions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auditvs.each do |auditv| %>
      <tr>
        <td><%= auditv.dataaudit.strftime('%d-%m-%Y') %> / <%= auditv.created_at.strftime('%H:%M')%> <b>Propera revisio:</b> <%= (auditv.created_at + 2.months).strftime('%d-%m-%Y') %> </td>
       <!-- <td><%= auditv.dataaudit %></td> -->
        <td><%= auditv.observacions %></td>
        <td><%= link_to 'Veure', auditv, :class=>'btn btn-primary btn-block' %></td>

        <td><%= link_to 'Editar capçalera', edit_auditv_path(auditv), :class=>'btn btn-warning btn-block' %></td>

        <td><%= link_to 'Esborrar', auditv, method: :delete, data: { confirm: 'Esborrar auditoria y plantilles relacionades. Estas segur?' }, :class=>'btn btn-danger btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova auditoria de Vidres/PD/BPH/BPM/FD/E-I', new_auditv_path, :class=>'btn btn-primary btn-block' %>
<%= link_to 'Plantilles de Vidres/PD/BPH/BPM/FD/E-I', vidres_path, :class=>'btn btn-primary btn-block' %>
<br>
<%= link_to 'Enrera', '\home\menu_auditories', :class=>'btn btn-primary btn-block' %>
<%= link_to 'Menu Principal', home_principal_path, :class=>'btn btn-primary btn-block' %>
<br>
<%= paginate @auditvs %>
<%= page_entries_info @auditvs %>

app/views/auditvs/new.html.erb
<h1 class="jumbotron">Nova auditoria de Vidres/PD/BPH/BPM/FD/E-I</h1>

<%= render 'form' %>
</br>
<%= link_to 'Cancel·lar', auditvs_path, :class=>'btn btn-primary btn-block' %>

app/views/auditvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @auditv.dataaudit %>
</p>

<p>
  <strong>Observacions:</strong>
  <%= @auditv.observacions %>
</p>

<!-- loop de todos los vidres -->

<table class="table table-condensed">
  <thead>
  <tr>
    <th>Nom</th>
    <th>Tipus</th>
    <th>Ubicació</th>
    <th>Descripció</th>
    <th>Recompte</th>
    <th>Estat Ok</th>
    <th>Observacions</th>
    <!-- <th>Auditoria</th> -->
    <th>Foto</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @vidres.each do |vidre| %>
      <tr>
        <td><%= vidre.nom %></td>
        <td><%= vidre.tipus %></td>
        <td><%= vidre.ubicacio %></td>
        <td><%= vidre.descripcio %></td>
        <td><%= image_tag vidre.fotobase, :style => 'width:175px;height:75px;'%></td>
        <td align="center"><%= vidre.recompte %></td>
        <td><%= check_box "vidre", "estat_ok", {:checked => vidre.estat_ok, :disabled => true}%></td>
        <td><%= vidre.observacions %></td>

        <!--  <td><%= vidre.auditv.id %></td> -->

        <td> <%= image_tag vidre.foto, :style => 'width:175px;height:75px;' %></td>

        <!-- <td><%= link_to 'Veure vidre', vidre %></td> -->

        <td><%= link_to 'Editar vidre', edit_vidre_path(vidre), :class=>'btn btn-primary btn-block' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</br>


<%= link_to 'Editar', edit_auditv_path(@auditv), :class=>'btn btn-primary btn-block' %> |
<%= link_to 'Enrera', auditvs_path, :class=>'btn btn-primary btn-block' %>